In [1]:
import pandas as pd

In [2]:
members = pd.read_csv(r"datasets/members.csv")
menu = pd.read_csv(r"datasets/menu.csv")
sales = pd.read_csv(r"datasets/sales.csv")

In [3]:
members.head()

  customer_id   join_date
0           A  07-01-2021
1           B  09-01-2021

In [4]:
menu.head()

   product_id product_name  price
0           1        sushi     10
1           2        curry     15
2           3        ramen     12

In [10]:
sales

   customer_id  order_date  product_id
0            A  01-01-2021           1
1            A  01-01-2021           2
2            A  07-01-2021           2
3            A  10-01-2021           3
4            A  11-01-2021           3
5            A  11-01-2021           3
6            B  01-01-2021           2
7            B  02-01-2021           2
8            B  04-01-2021           1
9            B  11-01-2021           1
10           B  16-01-2021           3
11           B  01-02-2021           3
12           C  01-01-2021           3
13           C  01-01-2021           3
14           C  07-01-2021           3

What is the total amount each customer spent at the restaurant?<br>
How many days has each customer visited the restaurant?<br>
What was the first item from the menu purchased by each customer?<br>
What is the most purchased item on the menu and how many times was it purchased by all customers?<br>
Which item was the most popular for each customer?<br>
Which item was purchased first by the customer after they became a member?<br>
Which item was purchased just before the customer became a member?<br>
What is the total items and amount spent for each member before they became a member?<br>
If each $1 spent equates to 10 points and sushi has a 2x points multiplier - how many points would each customer have?<br>
In the first week after a customer joins the program (including their join date) they earn 2x points on all items, not just sushi - how many points do customer A and B have at the end of January?

In [6]:
sales_menu_merge = pd.merge(sales, menu, on='product_id', how='left')

In [9]:
sales_menu_merge

   customer_id  order_date  product_id product_name  price
0            A  01-01-2021           1        sushi     10
1            A  01-01-2021           2        curry     15
2            A  07-01-2021           2        curry     15
3            A  10-01-2021           3        ramen     12
4            A  11-01-2021           3        ramen     12
5            A  11-01-2021           3        ramen     12
6            B  01-01-2021           2        curry     15
7            B  02-01-2021           2        curry     15
8            B  04-01-2021           1        sushi     10
9            B  11-01-2021           1        sushi     10
10           B  16-01-2021           3        ramen     12
11           B  01-02-2021           3        ramen     12
12           C  01-01-2021           3        ramen     12
13           C  01-01-2021           3        ramen     12
14           C  07-01-2021           3        ramen     12

In [7]:
all_merged = pd.merge(sales_menu_merge, members, on='customer_id', how='left')

In [25]:
all_merged["order_date"] = pd.to_datetime(all_merged["order_date"],format="%d-%m-%Y")
all_merged["join_date"] = pd.to_datetime(all_merged["join_date"],format="%d-%m-%Y")

In [26]:
all_merged

   customer_id order_date  product_id product_name  price  join_date
0            A 2021-01-01           1        sushi     10 2021-01-07
1            A 2021-01-01           2        curry     15 2021-01-07
2            A 2021-01-07           2        curry     15 2021-01-07
3            A 2021-01-10           3        ramen     12 2021-01-07
4            A 2021-01-11           3        ramen     12 2021-01-07
5            A 2021-01-11           3        ramen     12 2021-01-07
6            B 2021-01-01           2        curry     15 2021-01-09
7            B 2021-01-02           2        curry     15 2021-01-09
8            B 2021-01-04           1        sushi     10 2021-01-09
9            B 2021-01-11           1        sushi     10 2021-01-09
10           B 2021-01-16           3        ramen     12 2021-01-09
11           B 2021-02-01           3        ramen     12 2021-01-09
12           C 2021-01-01           3        ramen     12        NaT
13           C 2021-01-01           3        ramen     12        NaT
14           C 2021-01-07           3        ramen     12        NaT

In [27]:
solution1 = all_merged.groupby('customer_id')['price'].sum().reset_index()

In [28]:
solution1

  customer_id  price
0           A     76
1           B     74
2           C     36

In [29]:
solution2 = all_merged.groupby('customer_id')['order_date'].nunique().reset_index()

In [30]:
solution2

  customer_id  order_date
0           A           4
1           B           6
2           C           2

In [42]:
all_merged["first_date"] = (
    all_merged.groupby("customer_id")["order_date"]
              .transform("min"))

In [43]:
solution3 = all_merged[
    all_merged["order_date"] == all_merged["first_date"]
]

print(solution3[["customer_id", "product_name"]])

   customer_id product_name
0            A        sushi
1            A        curry
6            B        curry
12           C        ramen
13           C        ramen