In [1]:
import pandas as pd

In [2]:
members = pd.read_csv(r"datasets/members.csv")
menu = pd.read_csv(r"datasets/menu.csv")
sales = pd.read_csv(r"datasets/sales.csv")

In [3]:
members.head()

  customer_id   join_date
0           A  07-01-2021
1           B  09-01-2021

In [4]:
menu.head()

   product_id product_name  price
0           1        sushi     10
1           2        curry     15
2           3        ramen     12

In [5]:
sales.head()

  customer_id  order_date  product_id
0           A  01-01-2021           1
1           A  01-01-2021           2
2           A  07-01-2021           2
3           A  10-01-2021           3
4           A  11-01-2021           3

What is the total amount each customer spent at the restaurant?<br>
How many days has each customer visited the restaurant?<br>
What was the first item from the menu purchased by each customer?<br>
What is the most purchased item on the menu and how many times was it purchased by all customers?<br>
Which item was the most popular for each customer?<br>
Which item was purchased first by the customer after they became a member?<br>
Which item was purchased just before the customer became a member?<br>
What is the total items and amount spent for each member before they became a member?<br>
If each $1 spent equates to 10 points and sushi has a 2x points multiplier - how many points would each customer have?<br>
In the first week after a customer joins the program (including their join date) they earn 2x points on all items, not just sushi - how many points do customer A and B have at the end of January?

In [6]:
df = pd.merge(sales, menu, on='product_id', how='left')

In [7]:
print(df)

   customer_id  order_date  product_id product_name  price
0            A  01-01-2021           1        sushi     10
1            A  01-01-2021           2        curry     15
2            A  07-01-2021           2        curry     15
3            A  10-01-2021           3        ramen     12
4            A  11-01-2021           3        ramen     12
5            A  11-01-2021           3        ramen     12
6            B  01-01-2021           2        curry     15
7            B  02-01-2021           2        curry     15
8            B  04-01-2021           1        sushi     10
9            B  11-01-2021           1        sushi     10
10           B  16-01-2021           3        ramen     12
11           B  01-02-2021           3        ramen     12
12           C  01-01-2021           3        ramen     12
13           C  01-01-2021           3        ramen     12
14           C  07-01-2021           3        ramen     12

In [8]:
solution1 = df.groupby('customer_id')['price'].sum().reset_index()

In [9]:
print(solution1)

  customer_id  price
0           A     76
1           B     74
2           C     36

In [10]:
solution2 = df.groupby('customer_id')['order_date'].nunique().reset_index()
print(solution2)

  customer_id  order_date
0           A           4
1           B           6
2           C           2

In [11]:
df_sorted = df.sort_values('order_date', ascending = True)

In [12]:
df_sorted

   customer_id  order_date  product_id product_name  price
0            A  01-01-2021           1        sushi     10
1            A  01-01-2021           2        curry     15
6            B  01-01-2021           2        curry     15
12           C  01-01-2021           3        ramen     12
13           C  01-01-2021           3        ramen     12
11           B  01-02-2021           3        ramen     12
7            B  02-01-2021           2        curry     15
8            B  04-01-2021           1        sushi     10
2            A  07-01-2021           2        curry     15
14           C  07-01-2021           3        ramen     12
3            A  10-01-2021           3        ramen     12
4            A  11-01-2021           3        ramen     12
5            A  11-01-2021           3        ramen     12
9            B  11-01-2021           1        sushi     10
10           B  16-01-2021           3        ramen     12

In [13]:
first_occurence = df.drop_duplicates(subset='customer_id', keep='first')
first_occurence

   customer_id  order_date  product_id product_name  price
0            A  01-01-2021           1        sushi     10
6            B  01-01-2021           2        curry     15
12           C  01-01-2021           3        ramen     12

In [14]:
solution3 = first_occurence[['customer_id','product_name']]

In [15]:
solution3

   customer_id product_name
0            A        sushi
6            B        curry
12           C        ramen